---
title: "Benchmarking tree sequences"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarking tree sequences}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
slendr_present <- slendr::check_dependencies(python = TRUE, quit = FALSE)

knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>",
  fig.align = "center",
  fig.width = 8,
  fig.height = 5,
  dpi = 80,
  eval = FALSE && slendr_present && Sys.which("vcftools") != "" && Sys.which("convertf") != ""
)

abc_path <- system.file("examples/basics_abc.rds", package = "demografr")
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(admixr)

library(slendr)
init_env(quiet = TRUE)

chimp <- population("CHIMP", time = 7e6, N = 5000)
afr <- population("AFR", parent = chimp, time = 6e6, N = 15000)
eur <- population("EUR", parent = afr, time = 70e3, N = 3000)
nea <- population("NEA", parent = afr, time = 600e3, N = 1000, remove = 40e3)

gf <- gene_flow(from = nea, to = eur, rate = 0.03, start = 55000, end = 50000)

model <- compile_model(
  populations = list(chimp, nea, afr, eur),
  gene_flow = gf,
  generation_time = 30
)

nea_samples <- schedule_sampling(model, times = c(70000, 40000), list(nea, 1))

present_samples <- schedule_sampling(
  model, times = 0,
  list(chimp, 1),
  list(afr, 100), list(eur, 100)
)

schedule <- rbind(nea_samples, present_samples)

cowplot::plot_grid(
  plot_model(model, proportions = TRUE, samples = schedule),
  plot_model(model, proportions = TRUE, log = TRUE, samples = schedule),
  nrow = 1
)
```

```{r}
disk_run <- function(ts) {
  prefix <- file.path(tempdir(), "eigendata")
  suppressMessages(ts_eigenstrat(ts, prefix))
  eigen <- eigenstrat(prefix)

  suppressMessages(df <- f4ratio(data = eigen,
                                 X = ts_names(ts, split = "pop")$EUR,
                A = "NEA_1", B = "NEA_2", C = "AFR_1", O = "CHIMP_1", 
                params = list(blgsize = ts$sequence_length / 1e6 * 0.0025)) %>%
    .[c("X", "A", "B", "C", "O", "alpha")])

  nblocks <- capture.output(loginfo(df)) %>%
    grep("number of blocks for block jackknife", ., value = TRUE) %>%
    gsub("number of blocks for block jackknife: ", "", .) %>%
    as.integer

  result <- tibble(
    result = list(df),
    size = file.size(eigen$geno) + file.size(eigen$snp) + file.size(eigen$ind),
    nblocks = nblocks
  )

  unlink(eigen$geno)
  unlink(eigen$snp)
  unlink(eigen$ind)
  
  result
}

ts_run <- function(ts) {
  df <- ts_f4ratio(ts,
                   X = ts_names(ts, split = "pop")$EUR,
                   A = "NEA_1", B = "NEA_2", C = "AFR_1", O = "CHIMP_1")
  tibble(result = list(df), nblocks = NA)
}
```

```{r}
x <- Sys.time()
bench_df <- lapply(
  c(1, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000) * 1e3,
  function(sequence_length) {
# bench_df <- lapply(c(1, seq(1000, 100000, by = 3000)) * 1e3, function(sequence_length) {
  # sequence_length <- 100e3

  ts_time <- system.time(
    ts <- msprime(model, samples = schedule, sequence_length = sequence_length,
                  recombination_rate = 1e-8) %>%
      ts_mutate(mutation_rate = 1e-8)
  )

  disk_time <- system.time(disk_result <- disk_run(ts))
  memory_time <- system.time(memory_result <- ts_run(ts))
  
  df <- rbind(
    tibble(run = "ts simulation",
           time = ts_time["elapsed"],
           size = as.numeric(object.size(ts)),
           result = NA),
    tibble(run = "disk-based computation",
           time = disk_time["elapsed"],
           size = disk_result$size,
           result = disk_result$result),
    tibble(run = "memory-based computation",
           time = memory_time["elapsed"],
           size = NA,
           result = memory_result$result)
  ) %>%
    mutate(sequence_length = sequence_length) %>%
    tidyr::unnest(cols = c(result))
}) %>% do.call(rbind, .)
y <- Sys.time()
y - x

saveRDS(bench_df, "~/Desktop/bench_df.rds")
```

```{r}
p_bench <- bench_df %>%
  mutate(time = as.numeric(time)) %>%
  ggplot(aes(sequence_length  /1e6, time, color = run, group = run)) +
  geom_point() +
  geom_line() +
  labs(x = "sequence length [Mb]", y = "time (s)", color = "run") +
  theme_minimal()

cowplot::plot_grid(p_bench, p_bench + scale_x_log10() + scale_y_log10())
```


```{r}
bench_df %>%
  filter(run != "ts simulation") %>%
  mutate(time = as.numeric(time)) %>%
  select(run, X, alpha, sequence_length) %>%
  pivot_wider(names_from = run, values_from = alpha, names_prefix = "alpha_") %>%
  ggplot(aes(`alpha_disk-based computation`,
             `alpha_memory-based computation`,
             color = sequence_length  / 1e6)) +
  geom_point() +
  geom_abline(linetype = "dashed") +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = 0.03, linetype = "dotted") +
  geom_vline(xintercept = 0) +
  geom_vline(xintercept = 0.03, linetype = "dotted") +
  coord_cartesian(xlim = c(-0.1, 0.25), ylim = c(-0.1, 0.25)) +
  theme_minimal()
```
