#' Extract table of estimated model parameters
#'
#' @param abc ABC object generated by \code{perform_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting.
#'
#' @export
extract_summary <- function(abc, param = NULL) {
  posterior_df <- as.data.frame.matrix(quiet(summary(abc)))

  params <- subset_parameters(subset = param, all = colnames(posterior_df))

  posterior_df[, params, drop = FALSE]
}
