#' Extract slendr model constructed from the ABC posterior distribution
#'
#' @param abc ABC object generated by \code{perform_abc}
#' @param summary Which summary statistic of the posterior distribution to use? Options are
#'   "mode" (i.e. MAP estimates), "mean", or "median".
#'
#' @export
extract_model <- function(abc, summary = c("mode", "mean", "median")) {
  summary_df <- extract_posterior_summary(abc, summary)

  model <- attr(abc, "model")

  # replace Ne values in the scaffold model object with their ABC estimates
  for (param in summary_df$param) {
    if (grepl("^Ne_", param)) {
      pop <- gsub("Ne_", "", param)
      model$splits[model$splits$pop == pop, "N"] <- summary_df[summary_df$param == param, ]$value
    }
  }

  # TODO: this should create a whole new slendr model from scratch because the way
  # things are right now, the model$populations list is out of sync with the rest
  # of the slendr model tables
  model
}
