#' Extract table of estimated model parameters
#'
#' @param abc ABC object generated by \code{perform_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting.
#'
#' @export
extract_summary <- function(abc, param = NULL) {
  posterior_df <- as.data.frame.matrix(quiet(summary(abc)))

  params <- colnames(posterior_df)
  if (!is.null(param)) {
    param_re <- paste0(param, collapse = "|")
    params <- grep(param_re, params, value = TRUE)
    if (length(params) == 0)
      stop("No parameters fit the provided parameter subset", call. = FALSE)
  }

  posterior_df[, params, drop = FALSE]
}
