#' Plot histogram of posterior distributions
#'
#' @param x ABC object generated by \code{run_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting. If \code{NULL} (the default),
#'   all parameters will be extracted.
#' @param ... Formal ellipsis argument of the \code{plot} method (unused)
#'
#' @return A base R histogram plot
#'
#' @examples
#' # read inferred posterior distribution object from an example ABC run
#' abc_res <- readRDS(system.file("examples/basics_abc.rds", package = "demografr"))
#'
#' # plot histograms of posteriors for all parameters (in sequence)
#' # hist(abc_res)
#'
#' # plot only selected posteriors
#' # hist(abc_res, param = "gf_BC")
#' hist(abc_res, param = "^Ne_")
#'
#' @export hist.demografr_abc.abc
#' @export
hist.demografr_abc.abc <- function(x, param = NULL, ...) {
  parameters <- attr(x, "components")$parameters
  if (!is.null(param)) {
    parameters <- subset_parameters(subset = param, all = colnames(parameters))
    x$numparam <- length(parameters)
    x$names$parameter.names <- parameters
    x$adj.values <- x$adj.values[, parameters, drop = FALSE]
    x$unadj.values <- x$unadj.values[, parameters, drop = FALSE]
  }
  # after the filtering is done, use normal abc plotting (temporarily stripping away
  # demografr class annotation, replacing it with the abc class)
  class(x) <- "abc"
  graphics::hist(x, ...)
}
