#' Plot histogram of posterior distribution(s)
#'
#' @param x ABC object generated by \code{perform_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting. If \code{NULL} (the default),
#'   all parameters will be extracted.
#' @param ... Formal ellipsis argument of the \code{plot} method (unused)
#'
#' @return A base R histogram plot
#'
#' @export hist.demografr_abc.abc
#' @export
hist.demografr_abc.abc <- function(x, param = NULL, ...) {
  parameters <- attr(x, "parameters")
  if (!is.null(param)) {
    parameters <- subset_parameters(subset = param, all = colnames(attr(x, "parameters")))
    x$numparam <- length(parameters)
    x$names$parameter.names <- parameters
    x$adj.values <- x$adj.values[, parameters, drop = FALSE]
    x$unadj.values <- x$unadj.values[, parameters, drop = FALSE]
  }
  # after the filtering is done, use normal abc plotting (temporarily stripping away
  # demografr class annotation, replacing it with the abc class)
  class(x) <- "abc"
  graphics::hist(x, ...)
}
