#' Plot histogram of posterior distribution(s)
#'
#' @param x ABC object generated by \code{perform_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting.
#' @param ... Formal ellipsis argument of the \code{plot} method (unused)
#'
#' @export hist.demografr_abc.abc
#' @export
hist.demografr_abc.abc <- function(x, param = NULL, ...) {
  parameters <- attr(x, "parameters")
  if (!is.null(param)) {
    params <- subset_parameters(subset = param, all = colnames(attr(x, "parameters")))
    x$numparam <- length(params)
    x$names$parameter.names <- params
    x$adj.values <- x$adj.values[, params, drop = FALSE]
    x$unadj.values <- x$unadj.values[, params, drop = FALSE]
  }
  # after the filtering is done, use normal abc plotting (temporarily stripping away
  # demografr class annotation, replacing it with the abc class)
  browser()
  class(x) <- "abc"
  hist(x, ...)
}
