#' Plot diagnostics of posterior distribution(s)
#'
#' @param x ABC object generated by \code{run_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting. If \code{NULL} (the default),
#'   all parameters will be extracted.
#' @param ... Formal ellipsis argument of the \code{plot} method (unused)
#'
#' @return Used exclusively for printing
#'
#' @examples
#' # read inferred posterior distribution object from an example ABC run
#' abc_res <- readRDS(system.file("examples/basics_abc.rds", package = "demografr"))
#'
#' # plot diagnostics for all parameters (in sequence)
#' # plot(abc_res)
#'
#' # plot diagnostics only for selected parameters
#' plot(abc_res, param = "^Ne_")
#' # plot(abc_res, param = "gf_BC")
#'
#' @export plot.demografr_abc.abc
#' @export
plot.demografr_abc.abc <- function(x, param = NULL, ...) {
  parameters <- attr(x, "components")$parameters
  if (!is.null(param)) {
    params <- subset_parameters(subset = param, all = colnames(parameters))
    x$numparam <- length(params)
    x$names$parameter.names <- params
    x$adj.values <- x$adj.values[, params, drop = FALSE]
    x$residuals <- x$residuals[, params, drop = FALSE]
    x$unadj.values <- x$unadj.values[, params, drop = FALSE]
    parameters <- parameters[, params, drop = FALSE]
  }
  # after the filtering is done, use normal abc plotting (temporarily stripping away
  # demografr class annotation, replacing it with the abc class)
  class(x) <- "abc"
  plot(x, param = parameters, ...)
}
