#' Plot results of the cv4postpr procedure from the abc R package
#'
#' @param x ABC object generated by \code{perform_abc}
#' @param file Path to a PDF file for an output figure (if \code{NULL}, which is the default,
#'   the figure will not be saved to a file)
#' @param ... Formal ellipsis argument of the \code{plot} method
#'
#' @return Used exclusively for printing
#'
#' @export plot.demografr_cv
#' @export
plot.demografr_cv <- function(x, file = NULL, ...) {
  class(x) <- "cv4postpr"

  if (!is.null(file)) grDevices::pdf(file = file)

  plot(x, ...)

  if (!is.null(file)) grDevices::dev.off()
}
