#' Plot results of the cv4postpr procedure from the abc R package
#'
#' @param x ABC object generated by \code{perform_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting. If \code{NULL} (the default),
#'   all parameters will be extracted.
#' @param ... Formal ellipsis argument of the \code{plot} method (unused)
#'
#' @return Used exclusively for printing
#'
#' @export plot.demografr_cv
#' @export
plot.demografr_cv <- function(x, ...) {
  model_names <- attr(x, "model_names")
  class(x) <- "cv4postpr"
  plot(x, names.arg = model_names, ...)
}
