#' Plot posterior distribution of given parameters
#'
#' @param abc ABC object generated by \code{perform_abc}
#' @param param A character vector containing either parameter names to summarize,
#'   or a regex-like matches to be used for subsetting. If \code{NULL} (the default),
#'   all parameters will be extracted.
#' @param posterior Should an "adj"-usted or "unadj"-usted posterior be extracted?
#'   (Default is "adj").
#' @param facets Should individual distributions be plotted in separate facets? Default
#'   is \code{FALSE}.
#' @param file Output file for a figure saved via \code{ggsave}
#' @param ... Optional argument which will be passed to \code{ggsave}
#'
#' @return A ggplot2 plot object
#'
#' @export
plot_posterior <- function(abc, param = NULL, posterior = c("unadj", "adj"), facets = FALSE,
                           file = NULL, ...) {
  posterior <- match.arg(posterior)

  df <- extract_posterior(abc, param, posterior)

  param <- subset_parameters(subset = param, all = colnames(attr(abc, "components")$parameters))
  df <- df[df$param %in% param, ]

  # compute a given summary statistic of the posterior which will be added
  # as a vertical line overlaid on top of the distribution plot
  # summary_df <- extract_posterior_summary(abc, summary)
  # summary_df <- summary_df[summary_df$param %in% param, ]

  # priors <- attr(abc, "priors")
  # prior_samples <- simulate_priors(priors, 10000) %>% .[.$param %in% param, ]
  # xlim <- c(floor(min(prior_samples$value)), round(max(prior_samples$value)))

  p_facet <- if (facets) ggplot2::facet_wrap(~ param, scales = "free") else NULL

  p <- ggplot2::ggplot(df) +
    ggplot2::geom_density(ggplot2::aes(value, color = param, fill = param), alpha = 0.5) +
    ggplot2::scale_fill_discrete(drop = FALSE) +
    ggplot2::scale_color_discrete(drop = FALSE) +
    ggplot2::theme_minimal() +
    # ggplot2::coord_cartesian(xlim = xlim) +
    ggplot2::theme(strip.text.x = ggplot2::element_text(face = "bold", size = 13)) +
    p_facet

  if (!is.null(file))
    ggplot2::ggsave(file, plot = p, ...)
  else
    p
}

# extract_posterior_summary <- function(abc, summary = c("mode", "mean", "median")) {
#   summary <- match.arg(summary) %>% tools::toTitleCase()
#   summary_wide <- quiet(summary(abc))[sprintf("Weighted %s:", summary), ]
#   data.frame(
#     param = names(summary_wide),
#     value = as.vector(summary_wide),
#     stringsAsFactors = FALSE
#   )
# }
