#' Print a brief summary of the result of the \code{abc::cv4postpr} function
#'
#' @param x An object of the class \code{demografr_cv}, generated by \code{perform_cv}
#'
#' @return Used exclusively for printing
#'
#' @export summary.demografr_cv
#' @export
print.demografr_cv <- function(x, ...) {
  class(x) <- "cv4postpr"
  invisible(summary(x))
}
