#' Print a brief summary of the result of the \code{abc::postpr} function
#'
#' @param x An object of the class \code{demografr_postpr}, generated by \code{model_selection}
#'
#' @return Used exclusively for printing
#'
#' @export print.demografr_postpr
#' @export
#' @keywords internal
print.demografr_postpr <- function(x, ...) {
  class(x) <- "postpr"
  invisible(summary(x))
}
