#' Summary results of the \code{cv4postpr} procedure from the abc R package
#'
#' @param object ABC object generated by \code{perform_abc}
#' @param ... Formal ellipsis argument of the \code{summary} method (unused)
#'
#' @return ...
#'
#' @export summary.demografr_cv
#' @keywords internal
summary.demografr_cv <- function(object, ...) {
  class(object) <- "cv4postpr"
  summary(object, ...)
}
