#' Apply summary statistic functions to the simulated data
#'
#' @param data Data generated by \code{simulate_model}. Either a named list
#'   (when custom data-generating functions were used on user-defined
#'   simulation output files) or an object of the class \code{slendr_ts} (when
#'   a standard tree-sequence-producing simulation was ran by slendr itself).
#' @param functions A named list of data-generating functions
#'
#' @returns A named list of data frames, one summary statistic for each
#' @export
summarise_data <- function(data, functions) {
  functions_expr <- base::substitute(functions)

  # if the functions expression is just a symbol (i.e. was given as
  # a variable), evaluate it to get the actual list
  if (is.symbol(functions_expr)) {
    functions <- eval(functions_expr, envir = parent.frame())
  } else if (is.call(functions_expr)) {
    functions <- functions_expr
  }

  if (inherits(data, "slendr_ts")) {
    data <- list(ts = data)
  } else if ((is.list(data) && (all(is.null(names(data))) | any(names(data) == ""))) ||
             !is.list(data)) {
      stop("The `data` argument must be a named list produced by `simulate_model()`",
           call. = FALSE)
  }

  validate_user_functions(functions, valid_args = names(data))

  env <- list2env(data)
  stats <- evaluate(base::substitute(functions), env)

  stats
}
