#' Apply summary statistic functions to the simulated data
#'
#' @param data Data generated by \code{simulate_model}
#' @param functions A named list of data-generating functions
#'
#' @returns A named list of data frames, one summary statistic for each
#' @export
summarise_data <- function(data, functions) {
  functions_expr <- base::substitute(functions)

  # if the functions expression is just a symbol (i.e. was given as
  # a variable), evaluate it to get the actual list
  if (is.symbol(functions_expr)) {
    functions <- eval(functions_expr, envir = parent.frame())
  } else if (is.call(functions_expr)) {
    functions <- functions_expr
  }

  validate_user_functions(functions, valid_args = names(data))

  env <- list2env(data)
  stats <- evaluate(base::substitute(functions), env)

  stats
}
