#' Print a brief summary of a set of demografr simulations
#' @param x An object of the class \code{demografr_sims}, generated by \code{simulate_abc}
#' @return Used exclusively for printing
#' @export
print.demografr_sims <- function(x, ...) {
  n_iterations <- nrow(x$parameters)
  parameters <- colnames(x$parameters) %>% paste(collapse = ", ")
  summaries <- names(x$functions) %>% paste(collapse = ", ")

  cat("Number of simulation replicates:", n_iterations, "\n\n")

  cat("Model parameters to be estimated:\n    ")
  cat(parameters, "\n")

  cat("\n")

  cat("Summary statistics used:\n    ")
  cat(summaries, "\n")

  cat("\n")

  cat("Individual components of the <object> can be accessed as:\n")
  cat("  parameter matrix:            <object>$parameters\n")
  cat("  observed summary statistics: <object>$observed\n")
  cat("  summary functions:           <object>$functions\n")
  cat("  prior expressions:           <object>$priors\n")
}

# a function to silence the unnecessary summary() output on abc objects
# https://stackoverflow.com/a/54136863
quiet <- function(x) {
  sink(tempfile())
  on.exit(sink())
  invisible(force(x))
}

# Extract prior variable names as a character vector
prior_variables <- function(priors) {
  sapply(priors, function(p) as.character(as.list(p)[[2]]))
}
